### PR TITLE
review install

### PR DESCRIPTION
**Pull request by Andrei-Pozolotin**
1. use second-level `/*/`
```
    local unit_list=$(2>/dev/null grep -R -l -F -x -m1 "$marker" "$folder"/*/)
```

2. extend supported directives for [Section Options](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#%5BUnit%5D%20Section%20Options):
```
        case $directive in
            Requires|Requisite|BindsTo|OnFailure|Unit)
```

3. handling external-to-unit, i.e. folder-based "Forward" and "Reverse" dependencies

### CODE REVIEW

**Comment by fredleb** [comment]
/etc/systemd/system/*.requires are now properly copied to the initramfs image.

**Comment by Andrei-Pozolotin** [comment]
you mean you just tested? or just looked? or ...?

**Comment by fredleb** [comment]
Looked and tested but only that particular scenario.

**Comment by Andrei-Pozolotin** [comment]
great, thank you.

**Pull request merged**
