### PR TITLE
initrd nftables service

### PR DESCRIPTION
**Pull request by Andrei-Pozolotin**
firewall inside initramfs: `initrd-nftables.service`
many thanks to @vvl-rulez Vladislav, see:  #53 #55
```
# Provides firewall when running inside initrd
# see: https://wiki.archlinux.org/index.php/Nftables
```

### CODE REVIEW

**Comment by vvl-rulez** [comment]
> @vvl-rulez please review and test on live system #56

I've checked the code, seems all is okay.
To test in on system I need actual PKGBUILD - do you have it?

**Comment by Andrei-Pozolotin** [comment]
> I've checked the code, seems all is okay.

thank you

> I need actual PKGBUILD 

you did review, right? :-)
well, then you missed it: [PKGBUILD](https://github.com/random-archer/mkinitcpio-systemd-tool/blob/7e936bb0a939264a890bda19faaab1a1cf4e013c/PKGBUILD)

usage:
```
cd /tmp
git clone git@github.com:random-archer/mkinitcpio-systemd-tool.git
cd mkinitcpio-systemd-tool
git fetch origin pull/56/head:vvl-nftables
git checkout vvl-nftables
ls -las
makepkg -e
sudo pacman -U *.pkg.tar.xz
```

**Comment by vvl-rulez** [comment]
> well, then you missed it: [PKGBUILD](https://github.com/random-archer/mkinitcpio-systemd-tool/blob/7e936bb0a939264a890bda19faaab1a1cf4e013c/PKGBUILD)

Oh, really, sorry.

Package compiling successfull, but service at boot have some problems:
First, `Error: Could not process rule: Operation not supported`
I solved it by editing 
`InitrdCall=add_all_modules /netfilter/nft_*` to `InitrdCall=add_all_modules /netfilter/nf_tables*`

Now left errors like `Could not process rule: No such file or directory`
Trying to solve it. Will commit all fixes later

**Comment by vvl-rulez** [comment]
By the way...

> systemd-networkd[595]: Configuration file /etc/systemd/network/initrd-network.network is marked executable. Please remove executable permission bits. Proceeding anyway.
systemd-networkd[595]: Configuration file /etc/systemd/network/initrd-network.network is marked world-writable. Please remove world writability permission bits. Proceeding anyway.

**Comment by vvl-rulez** [comment]
> I solved it by editing
> `InitrdCall=add_all_modules /netfilter/nft_*` to `InitrdCall=add_all_modules /netfilter/nf_tables*`

Need both nf_tables* and nft_*. When I'm edited file to `InitrdCall=add_all_modules /netfilter/nf*`, all works fine. What we should do, this way or 2 lines?

**Comment by Andrei-Pozolotin** [comment]
> What we should do, this way or 2 lines?

I applied your review, thank you

> initrd-network.network is marked executable
> initrd-network.network is marked world-writable

I can not reproduce, please try to trace the origin of this bug

> really, sorry

no problem, I understand

please review test again on live system:
* positive check: remote ssh allowed
* negative check: remote port scan denied

**Comment by vvl-rulez** [comment]
>     * positive check: remote ssh allowed

Works

>     * negative check: remote port scan denied

Works

All seems good and working. Dont forget to add /etc/mkinitcpio-systemd-tool/config/initrd-nftables.conf to backup section of PKGBUILD (and for package maintainer too) :)

**Pull request merged**
