### PR TITLE
add knock realization

### PR DESCRIPTION
**Pull request by vvl-rulez**

### CODE REVIEW

**Comment by Andrei-Pozolotin** [comment]
@vvl-rulez 

1. thank you

2. did you test this in any way?

**Comment by Andrei-Pozolotin** [comment]
perhaps should use variables for port, etc?
https://wiki.nftables.org/wiki-nftables/index.php/Scripting#Defining_variables

**Comment by Andrei-Pozolotin** [comment]
why all config is commented out? activation is still done via `systemctl enable ...`

**Comment by vvl-rulez** [comment]
>     2. did you test this in any way?

Sure, I'm uning it on some machines

> perhaps should use variables for port, etc?

Done

> why all config is commented out? activation is still done via `systemctl enable ...`

Idea was in people make choise - use this block or not to use... But changed this

**Comment by vvl-rulez** [comment]
And I think need add PKGBUILD to repo - for opportunity to build and test git version to anyone...

**Pull request merged**
